window.CHILE_MED_CATALOG = [
  // 1. Presión y Corazón
  { name: "Losartán Potásico", active: "Losartán", category: "Presión / Corazón", dosage: "50 mg", color: "#3B82F6", colorName: "azul", meal: "WITH_MEAL", defaultTime: "13:30", freq: 12 },
  { name: "Losartán Potásico", active: "Losartán", category: "Presión / Corazón", dosage: "100 mg", color: "#3B82F6", colorName: "azul", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Enalapril Maleato", active: "Enalapril", category: "Presión / Corazón", dosage: "10 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 12 },
  { name: "Enalapril Maleato", active: "Enalapril", category: "Presión / Corazón", dosage: "20 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Amlodipino", active: "Amlodipino", category: "Presión / Corazón", dosage: "5 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Amlodipino", active: "Amlodipino", category: "Presión / Corazón", dosage: "10 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Atenolol", active: "Atenolol", category: "Presión / Corazón", dosage: "50 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Atenolol", active: "Atenolol", category: "Presión / Corazón", dosage: "100 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Carvedilol", active: "Carvedilol", category: "Presión / Corazón", dosage: "6.25 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 12 },
  { name: "Carvedilol", active: "Carvedilol", category: "Presión / Corazón", dosage: "12.5 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 12 },
  { name: "Carvedilol", active: "Carvedilol", category: "Presión / Corazón", dosage: "25 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 12 },
  { name: "Bisoprolol", active: "Bisoprolol", category: "Presión / Corazón", dosage: "2.5 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Bisoprolol", active: "Bisoprolol", category: "Presión / Corazón", dosage: "5 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Hidroclorotiazida", active: "Hidroclorotiazida", category: "Presión / Corazón", dosage: "25 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Hidroclorotiazida", active: "Hidroclorotiazida", category: "Presión / Corazón", dosage: "50 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Furosemida", active: "Furosemida", category: "Presión / Corazón", dosage: "40 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Espironolactona", active: "Espironolactona", category: "Presión / Corazón", dosage: "25 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Valsartán", active: "Valsartán", category: "Presión / Corazón", dosage: "80 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Valsartán", active: "Valsartán", category: "Presión / Corazón", dosage: "160 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Candesartán", active: "Candesartán", category: "Presión / Corazón", dosage: "8 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Candesartán", active: "Candesartán", category: "Presión / Corazón", dosage: "16 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Telmisartán", active: "Telmisartán", category: "Presión / Corazón", dosage: "40 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Telmisartán", active: "Telmisartán", category: "Presión / Corazón", dosage: "80 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Nifedipino Retard", active: "Nifedipino", category: "Presión / Corazón", dosage: "20 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "08:00", freq: 12 },
  { name: "Diltiazem", active: "Diltiazem", category: "Presión / Corazón", dosage: "60 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 8 },
  { name: "Aspirina Protect", active: "Ácido Acetilsalicílico", category: "Presión / Corazón", dosage: "100 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "13:30", freq: 24 },
  { name: "Clopidogrel (Plavix)", active: "Clopidogrel", category: "Presión / Corazón", dosage: "75 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "13:30", freq: 24 },
  { name: "Acenocumarol (Neosintrom)", active: "Acenocumarol", category: "Presión / Corazón", dosage: "4 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "18:00", freq: 24 },
  { name: "Xarelto", active: "Rivaroxabán", category: "Presión / Corazón", dosage: "10 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "13:30", freq: 24 },
  { name: "Xarelto", active: "Rivaroxabán", category: "Presión / Corazón", dosage: "20 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "13:30", freq: 24 },
  { name: "Eliquis", active: "Apixabán", category: "Presión / Corazón", dosage: "2.5 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 12 },
  { name: "Eliquis", active: "Apixabán", category: "Presión / Corazón", dosage: "5 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "08:00", freq: 12 },

  // 2. Diabetes y Azúcar
  { name: "Metformina Clorhidrato", active: "Metformina", category: "Diabetes / Azúcar", dosage: "500 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "13:30", freq: 12 },
  { name: "Metformina Clorhidrato", active: "Metformina", category: "Diabetes / Azúcar", dosage: "850 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "13:30", freq: 12 },
  { name: "Metformina Clorhidrato (XR)", active: "Metformina", category: "Diabetes / Azúcar", dosage: "1000 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "20:30", freq: 24 },
  { name: "Glafornil", active: "Metformina", category: "Diabetes / Azúcar", dosage: "850 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "13:30", freq: 12 },
  { name: "Glibenclamida", active: "Glibenclamida", category: "Diabetes / Azúcar", dosage: "5 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Glimepirida", active: "Glimepirida", category: "Diabetes / Azúcar", dosage: "2 mg", color: "#10B981", colorName: "verde", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Glimepirida", active: "Glimepirida", category: "Diabetes / Azúcar", dosage: "4 mg", color: "#3B82F6", colorName: "azul", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Jardiance", active: "Empagliflozina", category: "Diabetes / Azúcar", dosage: "10 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Jardiance", active: "Empagliflozina", category: "Diabetes / Azúcar", dosage: "25 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Forxiga", active: "Dapagliflozina", category: "Diabetes / Azúcar", dosage: "10 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Januvia", active: "Sitagliptina", category: "Diabetes / Azúcar", dosage: "50 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Januvia", active: "Sitagliptina", category: "Diabetes / Azúcar", dosage: "100 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Galvus", active: "Vildagliptina", category: "Diabetes / Azúcar", dosage: "50 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 12 },
  { name: "Trayenta", active: "Linagliptina", category: "Diabetes / Azúcar", dosage: "5 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Rybelsus (Semaglutida)", active: "Semaglutida", category: "Diabetes / Azúcar", dosage: "7 mg", color: "#FFFFFF", colorName: "blanca", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Rybelsus (Semaglutida)", active: "Semaglutida", category: "Diabetes / Azúcar", dosage: "14 mg", color: "#FFFFFF", colorName: "blanca", meal: "FASTING", defaultTime: "07:30", freq: 24 }
];
window.CHILE_MED_CATALOG.push(
  // 3. Tiroides y Hormonas
  { name: "Eutirox", active: "Levotiroxina", category: "Tiroides / Hormonas", dosage: "25 mcg", color: "#FFFFFF", colorName: "blanca", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Eutirox", active: "Levotiroxina", category: "Tiroides / Hormonas", dosage: "50 mcg", color: "#FFFFFF", colorName: "blanca", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Eutirox", active: "Levotiroxina", category: "Tiroides / Hormonas", dosage: "75 mcg", color: "#FFFFFF", colorName: "blanca", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Eutirox", active: "Levotiroxina", category: "Tiroides / Hormonas", dosage: "88 mcg", color: "#FFFFFF", colorName: "blanca", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Eutirox", active: "Levotiroxina", category: "Tiroides / Hormonas", dosage: "100 mcg", color: "#FFFFFF", colorName: "blanca", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Eutirox", active: "Levotiroxina", category: "Tiroides / Hormonas", dosage: "112 mcg", color: "#FFFFFF", colorName: "blanca", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Eutirox", active: "Levotiroxina", category: "Tiroides / Hormonas", dosage: "125 mcg", color: "#FFFFFF", colorName: "blanca", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Eutirox", active: "Levotiroxina", category: "Tiroides / Hormonas", dosage: "150 mcg", color: "#FFFFFF", colorName: "blanca", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Levotiroxina Sódica", active: "Levotiroxina", category: "Tiroides / Hormonas", dosage: "50 mcg", color: "#FFFFFF", colorName: "blanca", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Levotiroxina Sódica", active: "Levotiroxina", category: "Tiroides / Hormonas", dosage: "100 mcg", color: "#FFFFFF", colorName: "blanca", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Tapazol", active: "Tiamazol", category: "Tiroides / Hormonas", dosage: "5 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 12 },
  { name: "Alendronato", active: "Ácido Alendrónico", category: "Tiroides / Hormonas", dosage: "70 mg", color: "#FFFFFF", colorName: "blanca", meal: "FASTING", defaultTime: "07:30", freq: 24 },

  // 4. Colesterol y Lípidos
  { name: "Atorvastatina", active: "Atorvastatina", category: "Colesterol / Lípidos", dosage: "10 mg", color: "#FACC15", colorName: "amarilla", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },
  { name: "Atorvastatina", active: "Atorvastatina", category: "Colesterol / Lípidos", dosage: "20 mg", color: "#FACC15", colorName: "amarilla", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },
  { name: "Atorvastatina", active: "Atorvastatina", category: "Colesterol / Lípidos", dosage: "40 mg", color: "#FACC15", colorName: "amarilla", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },
  { name: "Lipitor", active: "Atorvastatina", category: "Colesterol / Lípidos", dosage: "20 mg", color: "#FFFFFF", colorName: "blanca", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },
  { name: "Rosuvastatina", active: "Rosuvastatina", category: "Colesterol / Lípidos", dosage: "10 mg", color: "#EF4444", colorName: "roja", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },
  { name: "Rosuvastatina", active: "Rosuvastatina", category: "Colesterol / Lípidos", dosage: "20 mg", color: "#EF4444", colorName: "roja", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },
  { name: "Crestor", active: "Rosuvastatina", category: "Colesterol / Lípidos", dosage: "10 mg", color: "#EF4444", colorName: "roja", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },
  { name: "Ezetimiba", active: "Ezetimiba", category: "Colesterol / Lípidos", dosage: "10 mg", color: "#FFFFFF", colorName: "blanca", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },
  { name: "Fenofibrato", active: "Fenofibrato", category: "Colesterol / Lípidos", dosage: "200 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "13:30", freq: 24 },
  { name: "Gemfibrozilo", active: "Gemfibrozilo", category: "Colesterol / Lípidos", dosage: "600 mg", color: "#FFFFFF", colorName: "blanca", meal: "FASTING", defaultTime: "07:30", freq: 12 },

  // 5. Estómago y Digestivo
  { name: "Omeprazol", active: "Omeprazol", category: "Estómago / Digestivo", dosage: "20 mg", color: "#EF4444", colorName: "roja", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Omeprazol", active: "Omeprazol", category: "Estómago / Digestivo", dosage: "40 mg", color: "#EF4444", colorName: "roja", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Nexium", active: "Esomeprazol", category: "Estómago / Digestivo", dosage: "20 mg", color: "#EF4444", colorName: "roja", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Nexium", active: "Esomeprazol", category: "Estómago / Digestivo", dosage: "40 mg", color: "#EF4444", colorName: "roja", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Lansoprazol", active: "Lansoprazol", category: "Estómago / Digestivo", dosage: "30 mg", color: "#EF4444", colorName: "roja", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Pantoprazol", active: "Pantoprazol", category: "Estómago / Digestivo", dosage: "40 mg", color: "#FACC15", colorName: "amarilla", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Famotidina", active: "Famotidina", category: "Estómago / Digestivo", dosage: "20 mg", color: "#FFFFFF", colorName: "blanca", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },
  { name: "Famotidina", active: "Famotidina", category: "Estómago / Digestivo", dosage: "40 mg", color: "#FFFFFF", colorName: "blanca", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },
  { name: "Domperidona", active: "Domperidona", category: "Estómago / Digestivo", dosage: "10 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "13:00", freq: 8 },
  { name: "Viadil (Pargeverina)", active: "Pargeverina", category: "Estómago / Digestivo", dosage: "10 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "13:30", freq: 8 },
  { name: "Viadil Compuesto", active: "Pargeverina + Metamizol", category: "Estómago / Digestivo", dosage: "1 comprimido", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "13:30", freq: 8 },
  { name: "Debridat (Trimebutino)", active: "Trimebutino", category: "Estómago / Digestivo", dosage: "200 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "13:00", freq: 8 },
  { name: "Lactulosa Jarabe", active: "Lactulosa", category: "Estómago / Digestivo", dosage: "15 ml", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },

  // 6. Dolor e Inflamación
  { name: "Paracetamol", active: "Paracetamol", category: "Dolor / Inflamación", dosage: "500 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "12:00", freq: 8 },
  { name: "Paracetamol", active: "Paracetamol", category: "Dolor / Inflamación", dosage: "1 g", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "12:00", freq: 8 },
  { name: "Kitadol", active: "Paracetamol", category: "Dolor / Inflamación", dosage: "500 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "12:00", freq: 8 },
  { name: "Kitadol Forte", active: "Paracetamol", category: "Dolor / Inflamación", dosage: "1 g", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "12:00", freq: 8 },
  { name: "Tapsin Noche", active: "Paracetamol + Clorfenamina", category: "Dolor / Inflamación", dosage: "1 sobre / comp.", color: "#3B82F6", colorName: "azul", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },
  { name: "Ibuprofeno", active: "Ibuprofeno", category: "Dolor / Inflamación", dosage: "400 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "13:30", freq: 8 },
  { name: "Ibuprofeno", active: "Ibuprofeno", category: "Dolor / Inflamación", dosage: "600 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "13:30", freq: 8 },
  { name: "Actron", active: "Ibuprofeno", category: "Dolor / Inflamación", dosage: "400 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "13:30", freq: 8 },
  { name: "Actron 600", active: "Ibuprofeno", category: "Dolor / Inflamación", dosage: "600 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "13:30", freq: 8 },
  { name: "Ketoprofeno", active: "Ketoprofeno", category: "Dolor / Inflamación", dosage: "100 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "13:30", freq: 12 },
  { name: "Ketoprofeno", active: "Ketoprofeno", category: "Dolor / Inflamación", dosage: "200 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "13:30", freq: 24 },
  { name: "Ketorolaco", active: "Ketorolaco", category: "Dolor / Inflamación", dosage: "10 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "13:30", freq: 8 },
  { name: "Celecoxib", active: "Celecoxib", category: "Dolor / Inflamación", dosage: "200 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Celebra", active: "Celecoxib", category: "Dolor / Inflamación", dosage: "200 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Meloxicam", active: "Meloxicam", category: "Dolor / Inflamación", dosage: "15 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Diclofenaco Sódico", active: "Diclofenaco", category: "Dolor / Inflamación", dosage: "50 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "13:30", freq: 8 },
  { name: "Diclofenaco Sódico", active: "Diclofenaco", category: "Dolor / Inflamación", dosage: "75 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "13:30", freq: 12 },
  { name: "Naproxeno", active: "Naproxeno", category: "Dolor / Inflamación", dosage: "550 mg", color: "#3B82F6", colorName: "azul", meal: "WITH_MEAL", defaultTime: "13:30", freq: 12 },
  { name: "Dorixina", active: "Clonixinato de Lisina", category: "Dolor / Inflamación", dosage: "125 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "13:30", freq: 8 },
  { name: "Dipirona / Metamizol", active: "Metamizol", category: "Dolor / Inflamación", dosage: "500 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "13:30", freq: 8 },
  { name: "Tramadol", active: "Tramadol", category: "Dolor / Inflamación", dosage: "50 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "13:30", freq: 8 },
  { name: "Zaldiar (Tramadol + Paracetamol)", active: "Tramadol + Paracetamol", category: "Dolor / Inflamación", dosage: "37.5 / 325 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "13:30", freq: 8 },
  { name: "Ciclobenzaprina", active: "Ciclobenzaprina", category: "Dolor / Inflamación", dosage: "10 mg", color: "#FACC15", colorName: "amarilla", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },

  // 7. Ánimo, Sueño y Neurología
  { name: "Sertralina", active: "Sertralina", category: "Ánimo / Sueño / Neuro", dosage: "50 mg", color: "#3B82F6", colorName: "azul", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Sertralina", active: "Sertralina", category: "Ánimo / Sueño / Neuro", dosage: "100 mg", color: "#3B82F6", colorName: "azul", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Altruline", active: "Sertralina", category: "Ánimo / Sueño / Neuro", dosage: "50 mg", color: "#3B82F6", colorName: "azul", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Escitalopram", active: "Escitalopram", category: "Ánimo / Sueño / Neuro", dosage: "10 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Escitalopram", active: "Escitalopram", category: "Ánimo / Sueño / Neuro", dosage: "20 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Ipran", active: "Escitalopram", category: "Ánimo / Sueño / Neuro", dosage: "10 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Fluoxetina", active: "Fluoxetina", category: "Ánimo / Sueño / Neuro", dosage: "20 mg", color: "#10B981", colorName: "verde", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Venlafaxina (XR)", active: "Venlafaxina", category: "Ánimo / Sueño / Neuro", dosage: "75 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Venlafaxina (XR)", active: "Venlafaxina", category: "Ánimo / Sueño / Neuro", dosage: "150 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Duloxetina", active: "Duloxetina", category: "Ánimo / Sueño / Neuro", dosage: "30 mg", color: "#3B82F6", colorName: "azul", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Duloxetina", active: "Duloxetina", category: "Ánimo / Sueño / Neuro", dosage: "60 mg", color: "#3B82F6", colorName: "azul", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Clonazepam", active: "Clonazepam", category: "Ánimo / Sueño / Neuro", dosage: "0.5 mg", color: "#EF4444", colorName: "roja", meal: "BEFORE_SLEEP", defaultTime: "22:30", freq: 24 },
  { name: "Clonazepam", active: "Clonazepam", category: "Ánimo / Sueño / Neuro", dosage: "2 mg", color: "#FFFFFF", colorName: "blanca", meal: "BEFORE_SLEEP", defaultTime: "22:30", freq: 24 },
  { name: "Rivotril", active: "Clonazepam", category: "Ánimo / Sueño / Neuro", dosage: "0.5 mg", color: "#EF4444", colorName: "roja", meal: "BEFORE_SLEEP", defaultTime: "22:30", freq: 24 },
  { name: "Rivotril", active: "Clonazepam", category: "Ánimo / Sueño / Neuro", dosage: "2 mg", color: "#FFFFFF", colorName: "blanca", meal: "BEFORE_SLEEP", defaultTime: "22:30", freq: 24 },
  { name: "Alprazolam", active: "Alprazolam", category: "Ánimo / Sueño / Neuro", dosage: "0.25 mg", color: "#FFFFFF", colorName: "blanca", meal: "BEFORE_SLEEP", defaultTime: "22:30", freq: 24 },
  { name: "Alprazolam", active: "Alprazolam", category: "Ánimo / Sueño / Neuro", dosage: "0.5 mg", color: "#3B82F6", colorName: "azul", meal: "BEFORE_SLEEP", defaultTime: "22:30", freq: 24 },
  { name: "Lorazepam", active: "Lorazepam", category: "Ánimo / Sueño / Neuro", dosage: "1 mg", color: "#FFFFFF", colorName: "blanca", meal: "BEFORE_SLEEP", defaultTime: "22:30", freq: 24 },
  { name: "Lorazepam", active: "Lorazepam", category: "Ánimo / Sueño / Neuro", dosage: "2 mg", color: "#FFFFFF", colorName: "blanca", meal: "BEFORE_SLEEP", defaultTime: "22:30", freq: 24 },
  { name: "Zopiclona", active: "Zopiclona", category: "Ánimo / Sueño / Neuro", dosage: "7.5 mg", color: "#3B82F6", colorName: "azul", meal: "BEFORE_SLEEP", defaultTime: "22:30", freq: 24 },
  { name: "Zolpidem", active: "Zolpidem", category: "Ánimo / Sueño / Neuro", dosage: "10 mg", color: "#FFFFFF", colorName: "blanca", meal: "BEFORE_SLEEP", defaultTime: "22:30", freq: 24 },
  { name: "Pregabalina", active: "Pregabalina", category: "Ánimo / Sueño / Neuro", dosage: "75 mg", color: "#EF4444", colorName: "roja", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },
  { name: "Pregabalina", active: "Pregabalina", category: "Ánimo / Sueño / Neuro", dosage: "150 mg", color: "#EF4444", colorName: "roja", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },
  { name: "Lyrica", active: "Pregabalina", category: "Ánimo / Sueño / Neuro", dosage: "75 mg", color: "#EF4444", colorName: "roja", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },
  { name: "Gabapentina", active: "Gabapentina", category: "Ánimo / Sueño / Neuro", dosage: "300 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "22:00", freq: 24 },
  { name: "Quetiapina", active: "Quetiapina", category: "Ánimo / Sueño / Neuro", dosage: "25 mg", color: "#EF4444", colorName: "roja", meal: "BEFORE_SLEEP", defaultTime: "22:30", freq: 24 },
  { name: "Quetiapina", active: "Quetiapina", category: "Ánimo / Sueño / Neuro", dosage: "100 mg", color: "#FACC15", colorName: "amarilla", meal: "BEFORE_SLEEP", defaultTime: "22:30", freq: 24 },
  { name: "Risperidona", active: "Risperidona", category: "Ánimo / Sueño / Neuro", dosage: "1 mg", color: "#FFFFFF", colorName: "blanca", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },
  { name: "Memantina", active: "Memantina", category: "Ánimo / Sueño / Neuro", dosage: "10 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Donepezilo", active: "Donepezilo", category: "Ánimo / Sueño / Neuro", dosage: "10 mg", color: "#FACC15", colorName: "amarilla", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },

  // 8. Antibióticos e Infecciones
  { name: "Amoxicilina", active: "Amoxicilina", category: "Antibióticos / Infecciones", dosage: "500 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 8 },
  { name: "Amoxicilina", active: "Amoxicilina", category: "Antibióticos / Infecciones", dosage: "875 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 12 },
  { name: "Amoxicilina + Ác. Clavulánico", active: "Amoxicilina + Clavulánico", category: "Antibióticos / Infecciones", dosage: "875 / 125 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 12 },
  { name: "Cefadroxilo", active: "Cefadroxilo", category: "Antibióticos / Infecciones", dosage: "500 mg", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "08:00", freq: 12 },
  { name: "Ciprofloxacino", active: "Ciprofloxacino", category: "Antibióticos / Infecciones", dosage: "500 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 12 },
  { name: "Azitromicina", active: "Azitromicina", category: "Antibióticos / Infecciones", dosage: "500 mg", color: "#FFFFFF", colorName: "blanca", meal: "FASTING", defaultTime: "08:00", freq: 24 },
  { name: "Nitrofurantoína", active: "Nitrofurantoína", category: "Antibióticos / Infecciones", dosage: "100 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 12 },
  { name: "Cotrimoxazol Forte", active: "Sulfametoxazol + Trimetoprima", category: "Antibióticos / Infecciones", dosage: "800 / 160 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 12 },
  { name: "Fluconazol", active: "Fluconazol", category: "Antibióticos / Infecciones", dosage: "150 mg", color: "#3B82F6", colorName: "azul", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Aciclovir", active: "Aciclovir", category: "Antibióticos / Infecciones", dosage: "400 mg", color: "#3B82F6", colorName: "azul", meal: "WITH_MEAL", defaultTime: "08:00", freq: 6 },

  // 9. Respiratorio y Alergias
  { name: "Loratadina", active: "Loratadina", category: "Respiratorio / Alergias", dosage: "10 mg", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Desloratadina", active: "Desloratadina", category: "Respiratorio / Alergias", dosage: "5 mg", color: "#3B82F6", colorName: "azul", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Levocetirizina", active: "Levocetirizina", category: "Respiratorio / Alergias", dosage: "5 mg", color: "#FFFFFF", colorName: "blanca", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },
  { name: "Clorfenamina", active: "Clorfenamina", category: "Respiratorio / Alergias", dosage: "4 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "22:00", freq: 8 },
  { name: "Salbutamol Inhalador", active: "Salbutamol", category: "Respiratorio / Alergias", dosage: "100 mcg (2 puff)", color: "#3B82F6", colorName: "azul", meal: "WITH_MEAL", defaultTime: "08:00", freq: 8 },
  { name: "Budesonida Inhalador", active: "Budesonida", category: "Respiratorio / Alergias", dosage: "200 mcg (2 puff)", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "08:00", freq: 12 },
  { name: "Montelukast", active: "Montelukast", category: "Respiratorio / Alergias", dosage: "10 mg", color: "#FACC15", colorName: "amarilla", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 },

  // 10. Vitaminas y Minerales
  { name: "Vitamina D3 (Colecalciferol)", active: "Colecalciferol", category: "Vitaminas / Minerales", dosage: "800 UI", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Vitamina D3 Forte", active: "Colecalciferol", category: "Vitaminas / Minerales", dosage: "50.000 UI", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Calcio + Vitamina D", active: "Calcio + D3", category: "Vitaminas / Minerales", dosage: "600 mg / 400 UI", color: "#FFFFFF", colorName: "blanca", meal: "WITH_MEAL", defaultTime: "13:30", freq: 12 },
  { name: "Neurobionta (B1, B6, B12)", active: "Complejo B", category: "Vitaminas / Minerales", dosage: "1 comprimido", color: "#EF4444", colorName: "roja", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Bion 3 Senior", active: "Multivitamínico + Probióticos", category: "Vitaminas / Minerales", dosage: "1 comprimido", color: "#3B82F6", colorName: "azul", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Sulfato Ferroso", active: "Hierro", category: "Vitaminas / Minerales", dosage: "200 mg", color: "#EF4444", colorName: "roja", meal: "FASTING", defaultTime: "07:30", freq: 24 },
  { name: "Ácido Fólico", active: "Ácido Fólico", category: "Vitaminas / Minerales", dosage: "1 mg", color: "#FACC15", colorName: "amarilla", meal: "WITH_MEAL", defaultTime: "08:00", freq: 24 },
  { name: "Magnesio (Citrato)", active: "Magnesio", category: "Vitaminas / Minerales", dosage: "400 mg", color: "#FFFFFF", colorName: "blanca", meal: "BEFORE_SLEEP", defaultTime: "22:00", freq: 24 }
);
